# Exemple de docker-compose.yml pour vos applications AFRICASA
# avec les labels Prometheus pour l'auto-discovery

version: '3.8'

services:
  backend:
    image: africasa/backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - METRICS_ENABLED=true
    labels:
      # Labels pour Prometheus auto-discovery
      - "prometheus.scrape=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"
      - "prometheus.service=africasa-backend"
      - "prometheus.env=production"
    networks:
      - africasa-network

  frontend:
    image: africasa/frontend:latest
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
    labels:
      - "prometheus.scrape=false"  # Frontend Next.js sans métriques par défaut
    depends_on:
      - backend
    networks:
      - africasa-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    labels:
      # Redis exporter sera déployé séparément
      - "prometheus.scrape=false"
    volumes:
      - redis_data:/data
    networks:
      - africasa-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9121"
      - "prometheus.path=/metrics"
      - "prometheus.service=redis"
      - "prometheus.env=production"
    depends_on:
      - redis
    networks:
      - africasa-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "9113:9113"  # nginx-prometheus-exporter
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=9113"
      - "prometheus.path=/metrics"
      - "prometheus.service=nginx"
      - "prometheus.env=production"
    depends_on:
      - backend
    networks:
      - africasa-network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx/nginx_status'
    depends_on:
      - nginx
    networks:
      - africasa-network

networks:
  africasa-network:
    driver: bridge

volumes:
  redis_data:
