services:
  # Base de données MongoDB (sans authentification pour les tests)
  mongodb:
    image: mongo:latest
    container_name: africasa-mongodb-compose
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - africasa-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: africasa-backend
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/africasa
      JWT_SECRET: africasa-super-secret-jwt-key-2024
      FRONTEND_URL: http://frontend:3000
      SKIP_EMAIL_VERIFICATION: "true"
      # Ajout de variables pour le debugging
      DEBUG: "true"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - africasa-network
    restart: unless-stopped
    volumes:
      - backend_uploads:/app/uploads
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      # Labels pour Prometheus auto-discovery
      - "prometheus.scrape=true"
      - "prometheus.port=5000"
      - "prometheus.path=/metrics"
      - "prometheus.service=africasa-backend"

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: africasa-frontend
    environment:
      NODE_ENV: development
      # CORRECTION: Pour accès depuis le navigateur (côté client)
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - africasa-network
    restart: unless-stopped
    labels:
      # Labels pour Prometheus auto-discovery
      - "prometheus.scrape=true"
      - "prometheus.port=3000"
      - "prometheus.path=/metrics"
      - "prometheus.service=africasa-frontend"

  # Prometheus pour le monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: africasa-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - africasa-network
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local
  prometheus_data:
    driver: local

networks:
  africasa-network:
    driver: bridge