---
# handlers file for ./roles/node_exporter
- name: Reload daemon and restart node_exporter
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
    enabled: true
