---
# defaults file for ./roles/grafana
grafana_version: "latest"
grafana_admin_user: "admin"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_port: 3000
grafana_data_dir: "/var/lib/grafana"
grafana_config_dir: "/etc/grafana"
grafana_log_dir: "/var/log/grafana"
grafana_plugins_dir: "/var/lib/grafana/plugins"
grafana_user: "grafana"
grafana_group: "grafana"

grafana_security:
  admin_user: "{{ grafana_admin_user }}"
  admin_password: "{{ grafana_admin_password }}"

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    url: "http://localhost:9090"
    access: "proxy"
    is_default: true

